[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_microros_distro = jazzy
board_microros_transport = wifi
monitor_speed = 115200
; QGP_EVMotor 的预编译库：PIO 只加 LIBPATH，需手动补 -lqgpmotor
build_flags =
  -Llib/QGP_EVMotor/src/esp32s3
  -lqgpmotor
lib_deps =
  https://github.com/micro-ROS/micro_ros_platformio.git
